name: Flask CI

on:
  push:
    branches:
      - main  # or whichever is your default branch
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies and set up venv
      run: |
        python -m pip install --upgrade pip
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Run tests inside venv
      run: |
        source env/bin/activate
        pytest

    - name: Flask run
      run: |
        source env/bin/activate
        flask run
