name: Flask CI

on:
  push:
    branches:
      - main # or whichever is your default branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10.5
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.5
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print working directory
        run: pwd

      - name: Run tests
        run: pytest tests
        env:
          PYTHONPATH: ./:$PYTHONPATH
