name: Flask Web App CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10.5
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.5
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests
        env:
          PYTHONPATH: ./:$PYTHONPATH

      # CD
      - name: Setup SSH and SCP
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PYTHONANYWHERE_SSH_KEY }}

      - name: SCP files to PythonAnywhere
        run: scp -r * misoto22@ssh.pythonanywhere.com:/path/to/your/app

      # Use the PythonAnywhere API to restart your web app:
      - name: Restart web app on PythonAnywhere
        run: |
          curl -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" \
               -X POST \
               https://www.pythonanywhere.com/api/v0/user/misoto22/webapps/misoto22.pythonanywhere.com/reload/
